/*
 * motor_driver.h
 *
 *  Created on: Sep 16, 2017
 *      Author: ronnymajani
 */

#ifndef MAIN_DRIVERS_INCLUDE_MOTOR_DRIVER_H_
#define MAIN_DRIVERS_INCLUDE_MOTOR_DRIVER_H_

// GPIO Pin Assignments
#define MOTOR_DRIVER1_GPIO_IN1_IN3
#define MOTOR_DRIVER1_GPIO_IN2_IN4
#define MOTOR_DRIVER1_GPIO_PWM

#define MOTOR_DRIVER2_GPIO_IN1_IN3
#define MOTOR_DRIVER2_GPIO_IN2_IN4
#define MOTOR_DRIVER2_GPIO_PWM


// Motor Pair Specific Pin Assignments
#define MOTOR_RIGHT_CW	MOTOR_DRIVER1_GPIO_IN1_IN3
#define MOTOR_RIGHT_CCW	MOTOR_DRIVER1_GPIO_IN2_IN4
#define MOTOR_RIGHT_SPD	MOTOR_DRIVER1_GPIO_PWM

#define MOTOR_LEFT_CW	MOTOR_DRIVER2_GPIO_IN1_IN3
#define MOTOR_LEFT_CCW	MOTOR_DRIVER2_GPIO_IN2_IN4
#define MOTOR_LEFT_SPD	MOTOR_DRIVER2_GPIO_PWM


#endif /* MAIN_DRIVERS_INCLUDE_MOTOR_DRIVER_H_ */
